# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'realwork' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for realwork
#  pod 'NLibrary', :git => 'https://github.com/NathanDVT/NLibrary.git', :branch => 'development'
#  pod 'Firebase/Auth'
#  pod 'Firebase/Firestore'
#  pod 'NLibrary', :git => 'https://github.com/NathanDVT/NLibrary.git', :branch => 'feature/add_obj_c'
  pod 'NLibrary', :path => '/Users/nngobale/Documents/Training 2020/Pod_Folder/NLibrary/NLibrary'
#     Add the Firebase pod for Google Analytics
#    pod 'Firebase/Analytics'
  
#  pod 'PromiseKit'
  target 'realworkTests' do
    inherit! :search_paths
    # Pods for testing
    
  end

end
