# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'realwork' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for realwork
  pod 'poddy', :path => '/Users/nngobale/Documents/Training 2020/Musico/realwork/poddy'

  target 'realworkTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
